- op: replace
  path: /spec/servers
  value:
    - port: {number: 443, name: https, protocol: HTTPS}
      hosts: ["radar.example.org"]
      tls:
        mode: SIMPLE
        credentialName: radar-tls                   # secret produit par cert-manager (namespace istio-system)
    - port: {number: 80, name: http, protocol: HTTP}
      hosts: ["radar.example.org"]
      tls:
        httpsRedirect: true
