apiVersion: apps/v1
kind: Deployment
metadata:
  name: radar-api
  namespace: radar
spec:
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone   # répartition sur 3 zones de disponibilité
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: radar-api
      containers:
        - name: radar-api
          resources:
            requests:
              cpu: 500m
              memory: 768Mi
            limits:
              memory: 1Gi
