apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: radar
labels:
  - pairs:
      app.kubernetes.io/part-of: radar
    includeSelectors: false
resources:
  - namespace.yaml
  - radar-api.yaml
  - signal-collector.yaml
  - radar-web.yaml
  - network-policies.yaml
